// AUTO-GENERATED by scripts/generate-route-templates.ts
// Do not edit by hand. Run `npm run generate-route-templates` to update.
// Plan rev 3, D-ROUTE-GEN.

export const ROUTE_TEMPLATES: readonly string[] = [
  "/newsletters/[slug]",
  "/competitions",
  "/hunts-course",
  "/newsletters",
  "/club-hunts",
  "/contact",
  "/lodge",
  "/range",
  "/join",
  "/"
] as const

function isDynamic(seg: string): boolean {
  return seg.startsWith('[') && seg.endsWith(']')
}

function isCatchAll(seg: string): boolean {
  return seg.startsWith('[...') && seg.endsWith(']')
}

function isOptionalCatchAll(seg: string): boolean {
  return seg.startsWith('[[...') && seg.endsWith(']]')
}

function matchesTemplate(pathname: string, template: string): boolean {
  const pSegs = pathname.split('/').filter(Boolean)
  const tSegs = template.split('/').filter(Boolean)

  // Optional catch-all: tail consumes zero or more
  if (tSegs.length > 0 && isOptionalCatchAll(tSegs[tSegs.length - 1])) {
    const headT = tSegs.slice(0, -1)
    if (pSegs.length < headT.length) return false
    return headT.every((seg, i) => isDynamic(seg) || seg === pSegs[i])
  }
  // Required catch-all: tail consumes one or more
  if (tSegs.length > 0 && isCatchAll(tSegs[tSegs.length - 1])) {
    const headT = tSegs.slice(0, -1)
    if (pSegs.length < headT.length + 1) return false
    return headT.every((seg, i) => isDynamic(seg) || seg === pSegs[i])
  }
  // Regular template: segment counts must match exactly
  if (pSegs.length !== tSegs.length) return false
  return tSegs.every((seg, i) => isDynamic(seg) || seg === pSegs[i])
}

/**
 * Normalise a runtime pathname to its route template.
 * Unknown paths (no matching template) pass through unchanged — by construction
 * Next.js can only render known templates, so an unknown pathname here means
 * either an error route or a static path not under app/.
 */
export function normaliseRoute(pathname: string): string {
  if (!pathname) return '/'
  // Strip query/hash (defensive; usePathname doesn't include them)
  const clean = pathname.split('?')[0].split('#')[0]
  if (ROUTE_TEMPLATES.includes(clean)) return clean
  for (const t of ROUTE_TEMPLATES) {
    if (matchesTemplate(clean, t)) return t
  }
  return clean
}
