/**
 * Walks app/** and emits a normalised list of route templates for analytics
 * (see plan rev 3, D-ROUTE-GEN). Output is committed; CI checks for drift.
 *
 * Conventions handled:
 *   - page.{js,jsx,ts,tsx,mdx}
 *   - Route groups (group) — skipped (not in URL)
 *   - Parallel slots @slot — skipped (not in URL)
 *   - Single dynamic [param]
 *   - Required catch-all [...param]
 *   - Optional catch-all [[...param]]
 *
 * Intercepting routes (..) (...) emit a build warning and are excluded.
 */
import { readdirSync, writeFileSync } from 'node:fs'
import { join, sep } from 'node:path'

const PAGE_RX = /^page\.(js|jsx|ts|tsx|mdx)$/

type FoundRoute = { template: string }

function walk(dir: string): FoundRoute[] {
  const out: FoundRoute[] = []
  let entries
  try {
    entries = readdirSync(dir, { withFileTypes: true })
  } catch {
    return out
  }
  for (const e of entries) {
    const full = join(dir, e.name)
    if (e.isDirectory()) {
      // Skip route groups (they don't appear in URLs)
      if (e.name.startsWith('(') && e.name.endsWith(')')) {
        if (e.name.startsWith('(.') || e.name.startsWith('(...')) {
          console.warn(`generate-route-templates: intercepting route ${e.name} not supported — skipping`)
          continue
        }
        out.push(...walk(full))
        continue
      }
      // Skip parallel slots (start with @)
      if (e.name.startsWith('@')) continue
      out.push(...walk(full))
    } else if (e.isFile() && PAGE_RX.test(e.name)) {
      out.push({ template: '__PAGE__:' + full })
    }
  }
  return out
}

function pathToTemplate(absPath: string, appRoot: string): string {
  // Strip absolute prefix down to "/..."
  const normalized = absPath.split(sep).join('/')
  const appAbs = appRoot.split(sep).join('/')
  let rel = normalized.startsWith(appAbs) ? normalized.slice(appAbs.length) : normalized
  // Strip trailing /page.{js,jsx,ts,tsx,mdx}
  rel = rel.replace(/\/page\.(js|jsx|ts|tsx|mdx)$/, '')
  // Remove (group) segments
  rel = rel.replace(/\/\([^)]+\)/g, '')
  if (rel === '' || rel === '/') return '/'
  return rel.replace(/\/$/, '')
}

const cwd = process.cwd()
const appRoot = join(cwd, 'app')

const found = walk(appRoot)
const templates = Array.from(
  new Set(found.map((f) => pathToTemplate(f.template.replace('__PAGE__:', ''), appRoot)))
)
  // Sort: longer (more specific) first so matching prefers the most specific template
  .sort((a, b) => b.split('/').length - a.split('/').length || b.length - a.length)

const generated = `// AUTO-GENERATED by scripts/generate-route-templates.ts
// Do not edit by hand. Run \`npm run generate-route-templates\` to update.
// Plan rev 3, D-ROUTE-GEN.

export const ROUTE_TEMPLATES: readonly string[] = ${JSON.stringify(templates, null, 2)} as const

function isDynamic(seg: string): boolean {
  return seg.startsWith('[') && seg.endsWith(']')
}

function isCatchAll(seg: string): boolean {
  return seg.startsWith('[...') && seg.endsWith(']')
}

function isOptionalCatchAll(seg: string): boolean {
  return seg.startsWith('[[...') && seg.endsWith(']]')
}

function matchesTemplate(pathname: string, template: string): boolean {
  const pSegs = pathname.split('/').filter(Boolean)
  const tSegs = template.split('/').filter(Boolean)

  // Optional catch-all: tail consumes zero or more
  if (tSegs.length > 0 && isOptionalCatchAll(tSegs[tSegs.length - 1])) {
    const headT = tSegs.slice(0, -1)
    if (pSegs.length < headT.length) return false
    return headT.every((seg, i) => isDynamic(seg) || seg === pSegs[i])
  }
  // Required catch-all: tail consumes one or more
  if (tSegs.length > 0 && isCatchAll(tSegs[tSegs.length - 1])) {
    const headT = tSegs.slice(0, -1)
    if (pSegs.length < headT.length + 1) return false
    return headT.every((seg, i) => isDynamic(seg) || seg === pSegs[i])
  }
  // Regular template: segment counts must match exactly
  if (pSegs.length !== tSegs.length) return false
  return tSegs.every((seg, i) => isDynamic(seg) || seg === pSegs[i])
}

/**
 * Normalise a runtime pathname to its route template.
 * Unknown paths (no matching template) pass through unchanged — by construction
 * Next.js can only render known templates, so an unknown pathname here means
 * either an error route or a static path not under app/.
 */
export function normaliseRoute(pathname: string): string {
  if (!pathname) return '/'
  // Strip query/hash (defensive; usePathname doesn't include them)
  const clean = pathname.split('?')[0].split('#')[0]
  if (ROUTE_TEMPLATES.includes(clean)) return clean
  for (const t of ROUTE_TEMPLATES) {
    if (matchesTemplate(clean, t)) return t
  }
  return clean
}
`

writeFileSync(join(cwd, 'lib/analytics/routeTemplates.generated.ts'), generated, 'utf8')
console.log(`generate-route-templates: emitted ${templates.length} templates`)
